spring:
  application:
    name: songapp
  config:
    import: optional:file:.env
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
     host: ${REDIS_HOST}
     port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${SERVER_PORT}
logging:
  level:
    org:
      springframework:
        data:
          redis=DEBUG:
        web: TRACE
    root: INFO
    com.ojasare.songapp: TRACE
  file:
    name: logs/song-app.log